// Grassmannian G(2,5) in P^9 via the Plucker embedding.
//
// Parametrizes 2-dimensional subspaces of a 5-dimensional space.
// Plucker coordinates p_{ij} (1 <= i < j <= 5), ordered lexicographically:
//   P.1 = p12,  P.2 = p13,  P.3 = p14,  P.4 = p15,
//   P.5 = p23,  P.6 = p24,  P.7 = p25,
//   P.8 = p34,  P.9 = p35,  P.10 = p45
//
// The ideal is generated by the 5 Plucker relations (quadrics),
// one for each choice of 4 indices from {1,2,3,4,5}.

function Grassmannian25(P)
    // P: ProjectiveSpace(K, 9)
    // Returns G(2,5) as a subscheme of P.
    rels := [
        P.1*P.8  - P.2*P.6  + P.3*P.5,   // {1,2,3,4}: p12*p34 - p13*p24 + p14*p23
        P.1*P.9  - P.2*P.7  + P.4*P.5,   // {1,2,3,5}: p12*p35 - p13*p25 + p15*p23
        P.1*P.10 - P.3*P.7  + P.4*P.6,   // {1,2,4,5}: p12*p45 - p14*p25 + p15*p24
        P.2*P.10 - P.3*P.9  + P.4*P.8,   // {1,3,4,5}: p13*p45 - p14*p35 + p15*p34
        P.5*P.10 - P.6*P.9  + P.7*P.8    // {2,3,4,5}: p23*p45 - p24*p35 + p25*p34
    ];
    return Scheme(P, rels);
end function;
